
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build_Project_with_Maven:
    uses: vandanabi/DevOps_repo2_assessment_2/.github/workflows/Mavenbuildtemplate.yml@develop
    with:
      file_path: \pom.xml
  Secret_Scan_using_template:
    uses: vandanabi/DevOps_repo2_assessment_2/.github/workflows/SecretScanningTemplate.yml@develop
  SCA_Scan_With_OWASP_DC:
    uses: vandanabi/DevOps_repo2_assessment_2/.github/workflows/SCAScanningTemplate.yml@develop
  SAST_Scan_Using_FindSecBugs:
    uses: vandanabi/DevOps_repo2_assessment_2/.github/workflows/SASTScanTemplate.yml@develop
    
