on:
  workflow_call:
    inputs:
      file_path:
        required: true
        type: string
  
jobs:
  BuildappWithGitHubActions:
    runs-on: ubuntu-latest
    steps:
    -  name: Checkout code
       uses: actions/checkout@v3
    -  name: Setup JDK 17
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'
         cache: maven
    -  name: Build with Maven
       run: mvn -B package --file ${{inputs.file_path}}
