# Creating a worflow to build this java project using maven
name: Maven build for this java app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  BuildthisappWithGutHubActions:
    runs-on: ubuntu-latest
    steps:
    -  uses: actions/checkout@v3
    -  name: Setup JDK 17
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'
         cache: maven
    -  name: Build with Maven
       run: mvn -B package --file pom.xml
    
    
